name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    uses: r7kamura/workflows/.github/workflows/github-release.yml@main
    secrets:
      github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
